version: "3.9"

services:
  api:
    build:
      context: ./cnd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=journal;Username=postgres;Password=lokokip999
      - Jwt__Key=DezeSleutelMoetMinimaal32TekensLangZijn!
      - Jwt__Issuer=JournalApi
      - Jwt__Audience=JournalApiUser
    networks:
      - journalnet

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lokokip999
    ports:
      - "5432:5432"
    networks:
      - journalnet

networks:
  journalnet:
