name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./cnd/cnd.sln

    - name: Build solution
      run: dotnet build ./cnd/cnd.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./cnd/JournalApi.Tests/JournalApi.Tests.csproj --configuration Release --no-restore --verbosity normal

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./cnd/cnd
        file: ./cnd/cnd/Dockerfile
        push: true
        tags: ohjcverhoeven/cnd:latest

